routes.py
from flask import Blueprint
from store import store
from flask import Flask
from flask import render_template, url_for, flash,session
from flask import current_app as app #
#from app import app #

#from app import db #
##
from models import User, Post, Product, Checkout
from forms import CheckoutForm, SearchForm
from forms import CheckoutForm, SearchForm
from flask import request, redirect
from forms import RegistrationForm
from forms import LoginForm
from flask_login import login_user
from flask_login import logout_user
from models import Comment
from forms import CommentForm
from flask_login import login_required, current_user
from sqlalchemy import desc
from datetime import datetime

app = store.app
db = store.db

routes = Blueprint('routes', __name__, static_folder='static', template_folder='templates')

@routes.route("/", methods=['GET', 'POST'])
@routes.route("/home", methods=['GET', 'POST'])
@routes.route("/home/<string:sort_by>", methods=['GET', 'POST'])
def home(sort_by=None):
    if 'visits' in session:
        session['visits'] = session.get('visits') + 1  # reading and updating session data
    else:
        session['visits'] = 1 # setting session data
        cart_item = {'Labrador Retriever': 0, 'German Shepherd': 0, 'Golden Retriever': 0,'Beagle': 0,'Poodle': 0, 'Pug': 0}
        session['cart_item'] = cart_item
    form = SearchForm()
    if form.validate_on_submit():
        search = form.search.data.capitalize()
        if Product.query.filter_by(title=search).first():
            flash(f'{search} Found')
            product =  Product.query.filter_by(title=search).first()
            return redirect(url_for('routes.product', product_id=product.id))
        else:
            flash(f'Dog Name: {search} Not Found')
            redirect(url_for('routes.home'))


    products=Product.query.order_by('title').all()
    if not(sort_by == None):
        if sort_by[0] == 'n':
            if sort_by[2] == 'd':
                products=Product.query.order_by(desc('title')).all()
        else:
            if sort_by[2] == 'd':
                products=Product.query.order_by(desc('price'))
            else:
                products=Product.query.order_by('price')
    return render_template('home.html',products=products,sort_by=sort_by,form=form)

@routes.route("/cart")
def cart():
    if not(current_user.is_authenticated):
        flash('You must login to do this.')
        return redirect(url_for('routes.login'))
    products=Product.query.all()
    total_price = 0 # Get the total price for the cart
    for product in products:
        total_price = total_price + product.price * session['cart_item'][product.title]
    return render_template('cart.html',products=products,total_price=total_price)


@routes.route("/wishlist")
def wishlist():
    if not(current_user.is_authenticated):
        flash('You must login to do this.')
        return redirect(url_for('routes.login'))
    if not('wishlist' in session):
        session['wishlist'] = {'Labrador Retriever': 0, 'German Shepherd': 0, 'Golden Retriever': 0,'Beagle': 0,'Poodle': 0, 'Pug': 0}  #BASKET😎

    products=Product.query.all()
    return render_template('wishlist.html',products=products)


@routes.route('/add/<string:loc>/<string:item_name>/<product_id>/<skey>')
def add(loc,item_name,product_id=None,skey=None):
    if not(current_user.is_authenticated):
        flash('You must login to do this.')
        return redirect(url_for('routes.login'))
    if skey in session:
        session[skey][item_name] = int(session[skey][item_name]) + 1
        session.modified = True

        if skey == 'wishlist':
            flash(f'Item Added! You added {item_name} to your {skey}!')
        else:
            flash(f'Item Added! You added {item_name} to your cart!')
    else:
        cart_item = {'Labrador Retriever': 0, 'German Shepherd': 0, 'Golden Retriever': 0,'Beagle': 0,'Poodle': 0, 'Pug': 0}   #BASKET😎
        session[skey] = cart_item
    return redirect(url_for("routes." + loc,product_id=product_id))

@routes.route('/subtract/<string:loc>/<string:item_name>/<product_id>/<skey>')
def subtract(loc,item_name,product_id=None,skey=None):
    if not(current_user.is_authenticated):
        flash('You must login to do this.')
        return redirect(url_for('routes.login'))
    if not(session[skey][item_name] == 0):
        if skey in session:
            session[skey][item_name] = int(session[skey][item_name]) - 1
            session.modified = True
        else:
            cart_item = {'Labrador Retriever': 0, 'German Shepherd': 0, 'Golden Retriever': 0,'Beagle': 0,'Poodle': 0, 'Pug': 0}    #BASKET😎
            session[skey] = cart_item

    return redirect(url_for("routes." + loc,product_id=product_id))

@routes.route('/clear/<string:loc>/<string:item_name>/<product_id>/<skey>')
def clear(loc,item_name,product_id=None,skey=None):
    if not(current_user.is_authenticated):
        flash('You must login to do this.')
        return redirect(url_for('routes.login'))
    if not(session[skey][item_name] == 0):
        if skey in session: #'cart_item'
            session[skey][item_name] = 0
            session.modified = True
        else:
            cart_item = {'Labrador Retriever': 0, 'German Shepherd': 0, 'Golden Retriever': 0,'Beagle': 0,'Poodle': 0, 'Pug': 0}
            session[skey] = cart_item

    return redirect(url_for("routes." + loc,product_id=product_id))

@routes.route("/about")
def about():
  return render_template('about.html', title='About')


@routes.route("/product/<int:product_id>")
def product(product_id):
    product = Product.query.get_or_404(product_id)
    comments = Comment.query.filter(Comment.product_id == product.id)
    form = CommentForm()
    return render_template('product.html', product=product, comments=comments, form=form)

@routes.route('/product/<int:product_id>/comment', methods=['GET', 'POST'])
@login_required
def product_comment(product_id):
    if not(current_user.is_authenticated):
        flash('You must login to do this.')
        return redirect(url_for('routes.login'))
    product = Product.query.get_or_404(product_id)
    form = CommentForm()
    if form.validate_on_submit():
        db.session.add(Comment(content=form.comment.data, product_id=product.id, author_id=current_user.id))
        db.session.commit()
        flash("Your comment has been added to the product page", "success")
        return redirect(f'/product/{product.id}')
    comments = Comment.query.filter(Comment.product_id == product.id)
    return render_template('product.html', product=product, comments=comments, form=form)


@routes.route("/register", methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(username=form.username.data,first_name=form.first_name.data,last_name=form.last_name.data,email=form.email.data, password=form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Registration successful!')
        login_user(user)
        return redirect(url_for('routes.home')) #Redirects to thank you for registering page

    return render_template('register.html', title='Register',form=form)

@routes.route("/login/<int:flag_comment>", methods=['GET', 'POST'])
@routes.route("/login", methods=['GET', 'POST'])
def login(flag_comment=None):
    if flag_comment == 1:
        flash('You must login to comment.')
        flag_comment=0

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is not None and user.verify_password(form.password.data):
            login_user(user)
            flash('Login successful!')
            return redirect(url_for('routes.home'))
        else:
            flash('That account does not exist!')





    return render_template('login.html', title='Login', form=form)

@routes.route("/logout")
def logout():
    logout_user()
    flash('Logout successful!')
    return redirect(url_for('routes.home'))




@routes.route("/checkout", methods=['GET', 'POST'])
def checkout():
    if not(current_user.is_authenticated):
        flash('You must login to do this.')
        return redirect(url_for('routes.login'))
    counter = 0
    products = products=Product.query.all()
    for product in products:
        if session['cart_item'][product.title] > 0:
            counter = counter + 1
    if counter == 0:
        flash('Cart is empty! Add items to check out.')
        return redirect(url_for('routes.invoice'))

    form = CheckoutForm()
    if form.validate_on_submit():
        checkout = Checkout(full_name=form.full_name.data,email=form.email.data,address=form.address.data,city=form.city.data, card_number=form.card_number.data, cvv=form.cvv.data, expiry_month=form.expiry_month.data,expiry_year=form.expiry_year.data)
        db.session.add(checkout)
        db.session.commit()
        flash('Payment Successful!')
        return redirect(url_for('routes.invoice')) #Redirects to invvoice

    return render_template('checkout.html',form=form)

@routes.route("/invoice")
def invoice():
    if not(current_user.is_authenticated):
        flash('You must login to do this.')
        return redirect(url_for('routes.login'))

    user = User.query.filter_by(email=current_user.email).first()
    checkout = Checkout.query.filter_by(email=current_user.email).first()
    if checkout == None:
        flash('You must checkout to receive an invoice.')
        return redirect(url_for('routes.checkout'))
    products=Product.query.all()
    total_price = 0 # Get the total price for the invoice
    for product in products:
        total_price = total_price + product.price * session['cart_item'][product.title]
    return render_template('invoice.html',checkout=checkout,products=products,user=user, total_price=total_price)

@routes.route("/ship")
def ship():
    if not(current_user.is_authenticated):
        flash('You must login to do this.')

templates/about.html
{% extends "layout.html" %}
{% block content %}
<div class="about-section">
  <h1>About Us</h1>
  <p><h3>PetsRus</h3>

PetsRus, Inc. is a doggy<br> provider comapny that not only sells the highest<br> quality breed of dogs, but also cares for the destitute and abused.  </p>

</div>

  <br><br>

<h2 style="text-align:center">Our Team</h2>
  <div class="card">
    <img src="{{ url_for('static', filename='team1.jpg') }}" style='width:100%';>
    <h1 style='padding:20px'>Professor Doug</h1>
    <p class="priced">CEO</p>
    <p id='product_content' style='padding:20px'>Professor Doug helped us secure Series A funding for our venture, he has obtained a PHD in Business Administration and is often quoted to be the most intelligent canine in the whole of Europe.</p>


  </div>
    <br><br>

{% endblock content %}

templates/cart.html
{% extends "layout.html" %}
{% block content %}
<!---->

<body onload="total_update()">
<!---->
{%set counter = namespace(header=0)%}
{%for product in products%}
{% if session['cart_item'][product.title] > 0 %}
{% set counter.header = counter.header  + 1 %}

{%endif%}
{%endfor%}

{% if counter.header  > 0 %}
<table class='cart text-align'>
<tbody>
<tr>
<th class='text-align wrapper'></th>
<th></th>
<th class='text-align wrapper'>Name</th>
<th></th>
<th class='text-align wrapper'>Description</th>
<th></th>
<th class='text-align wrapper'>Price</th>
<th></th>
<th class='text-align wrapper'></th>
<th></th>
<th>&nbsp;</th>
</tr>
{% endif %}
{% for product in products %}

  {% if session['cart_item'][product.title] > 0 %}
  <table class='cart text-align'>
  <tbody>
  <tr>
  <td class='wrapper'><a href="{{ url_for('routes.product', product_id=product.id) }}"><image src="{{ url_for('static', filename=product.image_file) }}" class='round' width="200" height="125"/></a></td>
  <td></td>
  <td class='wrapper text-align'><h4><a href="{{ url_for('routes.product', product_id=product.id) }}">{{ product.title }}</a><h4></td>
    <td></td>
  <td class='wrapper'><h5>{{ product.scontent }}<h5></td>
  <td></td>

  <td class='wrapper'><button type= 'button' class='cart button button3' onclick="location.href='{{url_for('routes.subtract',loc='cart',product_id='None',item_name=product.title,skey='cart_item')}}'; style='display: inline-block' ">-</button>&nbsp<div id='qty' style='display: inline-block'>{{session['cart_item'][product.title]}}</div>&nbsp<button type= 'button' class='cart button button2' onclick="location.href='{{url_for('routes.add',loc='cart',product_id='None',item_name=product.title,skey='cart_item')}}'; style='display: inline-block'; ">+</button></td>
  <td></td>
  <td class='wrapper space price'> <div class="sub_total" id='price_wished'>{{ (product.price * session['cart_item'][product.title]) | currencyformat }}</div></td>
  <td></td>
  <td class='wrapper'><a href="{{url_for('routes.clear',loc='cart',product_id='None',item_name=product.title,skey='cart_item')}}">❌</a></td>

  <td></td>
  </tr>
  <tr>
  <td>&nbsp;</td>
  <td></td>
  <td>&nbsp;</td>
  <td></td>
  <td>&nbsp;</td>
  <td></td>
  <td>&nbsp;</td>
  <td></td>
  <td></td>
  <td></td>
  <td>&nbsp;</td>
  </tr>
  </table>
  <hr>
  {% endif %}

{% endfor %}

{%if counter.header  > 0%}
<table class='footer cart text-align'>
<tr>

<td class='wrapper'>&nbsp;</td>
<td></td>
<td class='wrapper'>&nbsp;</td>
<td></td>
<td class='wrapper'>&nbsp;</td>
<td></td>
<td class='wrapper'><div class= 'price' id='tpricelabel'>Total Price: </div></td>
<td></td>
<td class='wrapper'><div class='price' id='total_price'>{{total_price | currencyformat}}</div></td>
<td></td>
<td class='wrapper'><button type= 'button' class='button checkout button5' onclick="location.href='{{url_for('routes.checkout')}}'; ">Checkout</button></td>
{% else %}
<h2 style='display:inline-block'>Shopping Cart Empty</h2> <button type= 'button' class='button checkout button4' onclick="location.href='{{url_for('routes.home')}}'; ">Home</button>
  {% endif %}
</tr>

</table>





{% endblock content %}

templates/home.html
{% extends "layout.html" %}
{% block content %}
<body onload='search_arrange()'>

  <form method="POST" action="" style='float:right;'>
  {{ form.csrf_token }}
  {{form.search(placeholder="Labrador Retriever")}} {{form.submit(class_='button button6')}} {% for error in form.search.errors %}
  <div class="alert alert-danger">{{ error }}<br> </div>
  {% endfor %}
  </form>
<div style='margin-left:41px'>
  <button type= 'button' class= 'button button2 sort' onclick="location.href='{{url_for('routes.home',sort_by='n_ascending')}}'; style='display: inline-block'; ">🔺</button> Name
<button type= 'button' class= 'button button2 sort' onclick="location.href='{{url_for('routes.home',sort_by='n_descending')}}'; style='display: inline-block'; ">🔻</button> ✣
<button type= 'button' class= 'button button2 sort' onclick="location.href='{{url_for('routes.home',sort_by='p_ascending')}}'; style='display: inline-block'; ">🔺</button> Price
<button type= 'button' class= 'button button2 sort' onclick="location.href='{{url_for('routes.home',sort_by='p_descending')}}'; style='display: inline-block'; ">🔻</button>
</div>
<br>

<!---->

<!---->


{% for product in products %}
<table class="dog-container" style="background-color:#edf0ee; float:left; margin-left:43px">
  <tr>
    <td colspan="2"  ><a href="{{ url_for('routes.product', product_id=product.id) }}"><image src="{{ url_for('static', filename=product.image_file) }}" class='round' width="400" height="250" /></a></td>

  </tr>
  <tr class='round'>
    <th colspan="2" class='text-align'><h3><a href="{{ url_for('routes.product', product_id=product.id) }}">{{ product.title }}</a><h3></th>
  </tr>
  <tr class='backstretch_lower'>
    <th class='space price' >{{product.price | currencyformat }}</th>

    <td><button type= 'button'  class='space button button2' onclick="location.href='{{url_for('routes.add',loc='home',product_id='None',item_name=product.title,skey='wishlist')}}'; style='display: inline-block'; ">Add To Wishlist</button>
      <button type= 'button'  class='space button button3' onclick="location.href='{{url_for('routes.add',loc='home',product_id='None',item_name=product.title,skey='cart_item')}}'; style='display: inline-block'; ">Add To Cart</button></td>
  </tr>
</table>






{% endfor %}


{% endblock content %}

templates/layout.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"> <!--Bootstrap for flask messages and form styling-->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<link rel=stylesheet type=text/css href="{{ url_for('static', filename='style.css') }}" />

<title>PetsRus</title>
<link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.ico') }}" />
</head>

<body onload='nav_change()'>

  <image src="{{ url_for('static', filename='doggy-banner.png') }}" width="100%" height="600" />

  <div class="banner">
      <a href="{{url_for('routes.home')}}"><image src="{{ url_for('static', filename='logo.png') }}"  width= "20%"  height="50px" style="min-width:200px; float:left;background-image: url('{{ url_for('static', filename='dogbackground.png') }}');"  /></a>



<nav>


        <div id="header" class="topnav " style="background-color:#35d1f0;">

         <a href="{{ url_for('routes.ship') }}" class="header" style="float:right;"><b> Shipping</b></a>
          <a href="{{ url_for('routes.invoice') }}" class="header" style="float:right;"><b> E-Invoice</b></a>
          <a href="{{ url_for('routes.checkout') }}" class="header" style="float:right;"><b> Checkout</b></a>

           <a href="{{ url_for('routes.cart') }}" class="header" style="float:right;"><b>&nbsp Shopping Cart</b></a>
            <a href="{{ url_for('routes.wishlist') }}" class="header" style="float:right;"><b> Wishlist</b></a>


          {% if not(current_user.is_authenticated) %}
          <a href="{{ url_for('routes.login') }}" class="header" style="float:right;"><b> Login</b></a>
          <a href="{{ url_for('routes.register') }}" class="header" style="float:right;"><b> Register</b></a>
          <a href="{{ url_for('routes.about') }}" class="header" style="float:right;"><b>About Us</b></a>
          <a href="{{ url_for('routes.home') }}" class="header" style="float:right;" ><b>Home</b> </a>
          <div href="{{ url_for('routes.home') }}" style="float:right; padding-top:15px; position:absolute;" class='header'> &nbsp <b class="header_greet">Hello, Guest!</b>

          {%else%}

          <a href="{{ url_for('routes.logout') }}" class="header" style="float:right;"><b>Logout&nbsp</b></a>
          <a href="{{ url_for('routes.about') }}" class="header" style="float:right;"><b>About Us</b></a>
          <a href="{{ url_for('routes.home') }}" class="header" style="float:right;" ><b>Home</b> </a>
           <div href="{{ url_for('routes.home') }}" style="float:right; padding-top:15px; position:absolute;" class='header'><b class="header_greet">&nbsp Hello, {{current_user.username}}! </b></div>



          {%endif%}


    </div>

      </div>


</nav>


      <br>





<div>
{% with messages = get_flashed_messages() %}
{% if messages %}
<ul class=flashes>
{% for message in messages %}
<div class="card_flash">
<div class="alert alert-info">
{{ message }}
</div>
</div>
{% endfor %}
</ul>
{% endif %}
{% endwith %}
</div>

<div id="content">
{% block content %}
{% endblock %}
</div>
<script>


var counter = 0

function nav_change() {
var url = location.href.split("/");
var navLinks = document.getElementsByTagName("nav")[0].getElementsByTagName("a");

var i=0;
var currentPage = url[url.length - 1];
for(i;i<navLinks.length;i++){
  var lb = navLinks[i].href.split("/");
  if(lb[lb.length-1] == currentPage) {
   navLinks[i].className = "active";

  }
  }
}

function total_update() {
// Make a loop to move through all sub_total class and add to total price
  total_price = 0
  var x = document.getElementsByClassName("sub_total");
  for(var i=0; i<x.length; i++) {
  var sub_total = document.getElementsByClassName('sub_total')[i].innerHTML
  var sub_total = parseFloat(sub_total.replace(/[^0-9.-]+/g,""));

  total_price = total_price + sub_total
}


  document.getElementById("total_price").innerHTML = '$' + total_price.toFixed(2);

}


function addCart(price) {
  var sub_total = document.getElementById("sub_total").innerHTML
  var sub_total = parseFloat(sub_total.replace(/[^0-9.-]+/g,""));
  sub_total = parseFloat(sub_total) + price
  sub_total = '$'+ sub_total.toFixed(2)
  document.getElementById("sub_total").innerHTML = sub_total;
}
function subCart(price) {
  var sub_total = document.getElementById("sub_total").innerHTML
  var sub_total = parseFloat(sub_total.replace(/[^0-9.-]+/g,""));
  sub_total = parseFloat(sub_total) - price
  sub_total = '$'+ sub_total.toFixed(2)
  document.getElementById("sub_total").innerHTML = sub_total;
}

function helpbox1(flag=0) {
document.getElementById("tag1").innerHTML = "Your full name should be provided";

if (flag) {
document.getElementById("tag1").innerHTML = "";
}

}
function helpbox2(flag=0) {
document.getElementById("tag2").innerHTML = "Provide a valid email address.";

if (flag) {
document.getElementById("tag2").innerHTML = "";
}

}

function helpbox3(flag=0) {
document.getElementById("tag3").innerHTML = "The address to deliver the item(s) to.";

if (flag) {
document.getElementById("tag3").innerHTML = "";
}

}

function helpbox4(flag=0) {
document.getElementById("tag4").innerHTML = "The city to deliver the item(s) to.";

if (flag) {
document.getElementById("tag4").innerHTML = "";
}

}

function helpbox5(flag=0) {
document.getElementById("tag5").innerHTML = "Provide a valid 16 digit card number.";

if (flag) {
document.getElementById("tag5").innerHTML = "";
}

}

function helpbox6(flag=0) {
document.getElementById("tag6").innerHTML = "Provide a 3 digit card security code.";

if (flag) {
document.getElementById("tag6").innerHTML = "";
}

}

function helpbox7(flag=0) {
document.getElementById("tag7").innerHTML = "Provide the 2 digit expiry month.";

if (flag) {
document.getElementById("tag7").innerHTML = "";
}

}

function helpbox8(flag=0) {
document.getElementById("tag8").innerHTML = "Provide the 4 digit expiry year.";

if (flag) {
document.getElementById("tag8").innerHTML = "";
}

}



</script>
</body>
</html>

templates/login.html
{% extends "layout.html" %}
{% block content %}
<form method="POST" action="" class='card_form' style='margin-left:380px;'>
{{ form.csrf_token }}
<div class="form-group">
{{ form.email.label }} <br>{{ form.email(class_="form-control",placeholder='example@gmail.com') }} </div><br>
{% for error in form.email.errors %}
<div class="alert alert-danger">{{ error }} <br>
</div>{% endfor %}
<div class="form-group">
{{ form.password.label }}<br> {{ form.password(class_="form-control") }} </div><br>
{% for error in form.password.errors %}
<div class="alert alert-danger">{{ error }} <br>
</div>{% endfor %}
<input type="submit" value="Login" class='button button2'> </form>
<br><br>
{% endblock content %}

templates/product.html
{% extends "layout.html" %}
{% block content %}
<!---->

<div class="card">
  <a href="{{ url_for('routes.product', product_id=product.id) }}"><img src="{{ url_for('static', filename=product.image_file) }}" style='width:100%';></a>
  <h1 style='padding:20px'>{{ product.title }}</h1>
  <p class="priced">{{product.price | currencyformat }}</p>
  <p id='product_content' style='padding:20px'>{{ product.lcontent }}</p>
  <button type= 'button' class='space button button2' onclick="location.href='{{url_for('routes.add',loc='product',product_id=product.id,item_name=product.title,skey='wishlist')}}'; ">Add To Wishlist</button>
  <button type= 'button' class='cart button button3' onclick="location.href='{{url_for('routes.add',loc='product',product_id=product.id,item_name=product.title,skey='cart_item')}}' ">Add to Cart</button>
<hr>
</div>


<!--product card inspired by https://www.w3schools.com/howto/howto_css_product_card.asp-->
<div class='product_footer'>
  <h2 class='grey'>Reviews</h2>
  </div>
{% for comment in comments %}
<div class='card_comment'>
  <div class='card_comment_content'>

<h3><b>{{ comment.user.username.upper() }}</b></h3> {{comment.date}} <br><br>

<p style='font-size:18px'>{{ comment.content }} &nbsp  </p>
</div>
</div>
{% endfor %}

<form method="POST" action="{{ url_for('routes.product_comment', product_id=product.id) }}">

  {{ form.hidden_tag() }}

<div class="">
  <div class='product_footer'>
       <h2>{{ form.comment.label }} </h2>{{ form.comment }} </div>
       {% for error in form.comment.errors %}
<div class="alert alert-danger">{{ error }}</div>
 {% endfor %}
</div>
{% if current_user.is_authenticated %}
<div class="">

      {{ form.submit(class_='button button2') }}
     </div>
    {% else %}
    <br>
    <button type="button" name="button login comment button" class='button button2' onclick="location.href='{{url_for('routes.login',flag_comment='1')}}' ">Post Comment</button>
     {% endif %}
   </form>
   <br><br>
{% endblock content %}

templates/registered.html
{% extends "layout.html" %}
{% block content %}
<h1>Thank You For Registering, {{first_name}} {{last_name}}!</h1>
{% endblock content %}

templates/wishlist.html
{% extends "layout.html" %}
{% block content %}

<!---->
{%set counter = namespace(header=0)%}
{%for product in products%}
{% if session['wishlist'][product.title] > 0 %}
{% set counter.header = counter.header  + 1 %}

{%endif%}
{%endfor%}

{% if counter.header  > 0 %}

<table class='cart text-align'>
<tbody>
<tr>
<th class='text-align wrapper'></th>
<th></th>
<th class='text-align wrapper'>Name</th>
<th></th>
<th class='text-align wrapper'>Description</th>
<th></th>
<th class='text-align wrapper'>Price</th>
<th></th>
<th class='text-align wrapper'></th>
<th></th>
<th>&nbsp;</th>
</tr>
{% endif %}

{% for product in products %}

  {% if session['wishlist'][product.title] > 0 %}
  <table class='cart text-align'>
  <tbody>
  <tr>
  <td class='wrapper'><a href="{{ url_for('routes.product', product_id=product.id) }}"><image src="{{ url_for('static', filename=product.image_file) }}" class='round' width="200" height="125"/></a></td>
  <td></td>
  <td class='wrapper text-align'><h4><a href="{{ url_for('routes.product', product_id=product.id) }}">{{ product.title }}</a><h4></td>
    <td></td>
  <td class='wrapper'><h5>{{ product.scontent }}<h5></td>
  <td></td>
<td class='wrapper space price' id='price_wished'> <div class="sub_total">{{ product.price | currencyformat }}</div></td>

  <td></td>
    <td class='wrapper'>  <button type= 'button' class='cart button button3' onclick="location.href='{{url_for('routes.add',loc='wishlist',product_id='None',item_name=product.title,skey='cart_item')}}'; ">Add to cart</button></td>
  <td></td>
  <td class='wrapper'><a href="{{url_for('routes.clear',loc='wishlist',product_id='None',item_name=product.title,skey='wishlist')}}">❌</a></td>

  <td></td>
  </tr>
  <tr>
  <td>&nbsp;</td>
  <td></td>
  <td>&nbsp;</td>
  <td></td>
  <td>&nbsp;</td>
  <td></td>
  <td>&nbsp;</td>
  <td></td>
  <td></td>
  <td></td>
  <td>&nbsp;</td>
  </tr>
  </table>
  <hr>
  {% endif %}

{% endfor %}




{%if counter.header  > 0%}
<table class='footer cart text-align'>
<tr>

<td class='wrapper'>&nbsp;</td>
<td></td>
<td class='wrapper'>&nbsp;</td>
<td></td>
<td class='wrapper'>&nbsp;</td>
<td></td>
<td class='wrapper'><div class= 'price' id='tpricelabel'></div></td>
<td></td>
<td class='wrapper'><div class='price' id='total_price'></div></td>
<td></td>
<td class='wrapper'><button type= 'button' class='button checkout button4' onclick="location.href='{{url_for('routes.cart')}}'; ">Shopping Cart</button></td>
{% else %}

<h2 style='display:inline-block'>Wishlist Empty</h2> <td class='wrapper'><button type= 'button' class='button checkout button4' onclick="location.href='{{url_for('routes.cart')}}'; ">Shopping Cart</button></td>
  {% endif %}

</tr>
</table>


{% endblock content %}